version: '3.1'

services:

  db:
    image: postgres
    container_name: jobs-db
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
